### ISSUE TITLE
On fresh install, quasar-with-quasar-cli doesn't seem to support testing with jest

### ISSUE THREAD

**Issue by onexdata** [paulvanbladel/quasar-jest#1]
When I git clone, switch to quasar-with-quasar-cli folder, npm install, then run jest, I get the infamous ES6/Babel issue "import" is an unexpected token.

I tried the quasar-with-vue-cli folder and can get the "npm run test:unit" working, but see it runs vue-cli-service test:unit and I'm not familiar with that.

Trying to get my Quasar project to support Jest but using Babel 7, and thought this repo might point me in the right direction.

**Comment by onexdata** [comment]
Also, quasar-with-quasar-cli uses Babel 7, quasar-with-vue-cli does not, so really hoping to get the quasar-with-quasar-cli folder working with Jest.  Help would greatly be appreciated.

**Comment by paulvanbladel** [comment]
@onexdata 
This is a mysterious issue.
Well, on my side, I had that same error, until today when  I updated the repo with the latest 'insights'.
What I did now (in order to get closer to your setup), i deleted my node_modules folder (on the quasar-with-quasar-cli project), and did npm install again and voila
```/quasar-jest/quasar-with-vue-cli (master)
$ jest
 PASS  tests/unit/example.spec.js
 PASS  tests/unit/quasar-btn.spec.js

Test Suites: 2 passed, 2 total
Tests:       6 passed, 6 total
Snapshots:   0 total
Time:        2.786s
Ran all test suites.
```
I saw that package.json does not contain the jest package. I added it now as a dev dependency.

What you can try (in order to get closer to my config) is install @vue/cli  and jest locally with -g.

**Comment by onexdata** [comment]
I am a little confused.  I am already able to get Jest to run in the quasar-with-vue-cli folder.  Your commit looks like it was for the /quasar-with-vue-cli/package.json so it would not affect the quasar-with-quasar-cli/ folder, right?

I installed @vue/cli and jest locally with -g as suggested.

vue -V
3.2.1

jest -v
23.6.0

When running jest in /quasar-with-quasar-cli/ I still get...

jest
 FAIL  tests/core/first.spec.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    C:\life.io\web-31\quasar-jest\quasar-with-quasar-cli\tests\core\first.spec.js:2
    import { add } from '../../src/core/first';
    ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)

 FAIL  tests/unit/example.spec.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    C:\life.io\web-31\quasar-jest\quasar-with-quasar-cli\tests\unit\example.spec.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import Quasar, * as All from 'quasar';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        2.526s
Ran all test suites.

**Comment by onexdata** [comment]
p.s. I also cleared my quasar-with-quasar-cli/node_modules folder and did npm install before trying to run jest.

**Comment by onexdata** [comment]
I found what I believe is the issue... Can you confirm?

1) Jest in /quasar-with-quasar-cli/ folder fails
2) Jest in /quasar-with-vue-cli/ folder works
2) Copying /quasar-with-vue-cli/babel.config.js to /quasar-with-quasar-cli/babel.config.js makes #1 work

Is that accurate?  And do you have any insight as to why?  Does Babel 7 require a babel.config.js file instead of a .babelrc file?

**Comment by onexdata** [comment]
According to https://babeljs.io/docs/en/configuration ...

What's your use case?
You want to programmatically create the configuration?
You want to compile node_modules?
**babel.config.js is for you!**

You have a static configuration that only applies to your simple single package?
**.babelrc is for you!**

The Guy Fieri is your hero?
We recommend to use the babel.config.js format. Babel itself is using it.

...it *sounds* (?) like the cheeky Facebook dev is saying you can't compile node_modules unless you use babel.config.js, which would explain why the quasar folder fails until it places config in babel.config.js... but holy crap is this poor documentation.

**Comment by onexdata** [comment]
One final update (I think)... this conclusively proves you *need* babel.config.js instead of .babelrc for Quasar to work properly...

Steps to reproduce:

1) Observe quasar-with-quasar-cli folder fails with jest.
2) Copy babel.config.js from quasar-with-vue-cli folder to quasar-with-quasar-cli folder.  Jest now works in quasar-with-quasar-cli folder.
3) Edit .babelrc file and babel.config.js file: Make babel.config.js *identical* in every way to .bablerc file except for "module.exports =" at the top of the babel.config.js file.
4) Using .babelrc file, jest fails.
5) Using babel.config.js file, jest works.

**Note** Jest caches and will give false positives with this unless you run "jest --no-cache"

**Comment by paulvanbladel** [comment]
here, both projects work.
In my view, babelrc and babel.config are the same.
Indeed, jest --no-cache is useful :)

**Comment by paulvanbladel** [comment]
@onexdata you got it working?
